spring:
   application:
      name: transaction_service
   profiles:
      active: ${ACTIVE_PROFILE:dev}
   datasource:
      url: jdbc:postgresql://${POSTGRES_SQL_HOST}:${POSTGRES_SQL_PORT}/${POSTGRES_SQL_DB}
      username: ${POSTGRES_SQL_USERNAME}
      password: ${POSTGRES_SQL_PASSWORD}
      driver-class-name: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: create
      show-sql: true
      properties:
         hibernate:
            jdbc:
               time_zone: UTC
            format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
   kafka:
      bootstrap-servers: localhost:9092
      consumer:
         group-id: transaction-group
         auto-offset-reset: earliest

